name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Create uv virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Install ruff
        run: uv pip install ruff black
      - name: Lint
        run: |
          uv run ruff check .
          uv run black --check .
      - name: Test
        run: uv run pytest -q
