name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Lint
        run: |
          uv run --frozen ruff check .
          uv run --frozen black --check .
      - name: Test
        run: PYTEST_DISABLE_PLUGIN_AUTOLOAD="" uv run --frozen pytest -q
